version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Btns
  - dilshan
  - DONOTSAVECHANGES
  - edittext
  - ICYMI
  - Pexels
  - Photoshop
  - Piacquadio
  - statictext
ignoreWords: []
import: []
